export const lightTheme = {
  body: '#E2E2E2',
  text: '#363537',
  toggleBorder: '#000',
  primary: '#E2E2E2',
  background: '#000',
  contactMeButtonText: '#fff',
  contactMeButtonBackground: '#000',
  contactMeBackground: '#000',
  seeMoreButtonText: '#000',
  commentsBackground: '#fff',
  commentsInput: '#E2E2E2',
  commentsBubble: '#E2E2E2',
};

export const darkTheme = {
  body: '#000',
  text: '#FAFAFA',
  toggleBorder: '#6B8096',
  primary: '#363537',
  background: '#E2E2E2',
  contactMeButtonText: '#000',
  contactMeButtonBackground: '#fff',
  contactMeBackground: '#000',
  seeMoreButtonText: '#fff',
  commentsBackground: '#fff',
  commentsInput: '#000',
  commentsBubble: '#E2E2E2',
};

export const blueTheme = {
  body: '#219ebc',
  text: '#363537',
  toggleBorder: '#023047',
  primary: '#E2E2E2',
  background: '#000',
  contactMeButtonText: '#fff',
  contactMeButtonBackground: '#000',
  contactMeBackground: '#000',
  seeMoreButtonText: '#000',
  commentsBackground: '#fff',
  commentsInput: '#219ebc',
  commentsBubble: '#E2E2E2',
};

export const redTheme = {
  body: '#780000',
  text: '#FAFAFA',
  toggleBorder: '#6B8096',
  gradient: 'linear-gradient(#091236, #1E215D)',
  primary: '#363537',
  background: '#fff',
  contactMeButtonText: '#000',
  contactMeButtonBackground: '#fff',
  contactMeBackground: '#000',
  seeMoreButtonText: '#fff',
  commentsBackground: '#fff',
  commentsInput: '#780000',
  commentsBubble: '#E2E2E2',
};
