export const lightTheme = {
  primary: '#fff',
  secondary: '#f5f3f4',
  accent: '#202020',
  text: '#000',
  toggleBorder: '#000',
  contactMeButtonText: '#fff',
  contactMeButtonBackground: '#000',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#000',
  seeMoreButtonText: '#000',
  commentsBackground: '#fff',
  commentsInput: '#E2E2E2',
  commentsBubble: '#E2E2E2',
};

export const darkTheme = {
  primary: '#363537',
  secondary: '#8d99ae',
  accent: '#2b2d42',
  text: '#000',
  toggleBorder: '#6B8096',
  contactMeButtonText: '#000',
  contactMeButtonBackground: '#fff',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#fff',
  seeMoreButtonText: '#fff',
  commentsBackground: '#fff',
  commentsInput: '#000',
  commentsBubble: '#E2E2E2',
};

export const blueTheme = {
  primary: '#fff',
  secondary: '#8d99ae',
  accent: '#2b2d42',
  text: '#000',
  toggleBorder: '#6B8096',
  contactMeButtonText: '#fff',
  contactMeButtonBackground: '#000',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#fff',
  seeMoreButtonText: '#000',
  commentsBackground: '#fff',
  commentsInput: '#219ebc',
  commentsBubble: '#E2E2E2',
};

export const redTheme = {
  primary: '#fff',
  secondary: '#8d99ae',
  accent: '#2b2d42',
  text: '#000',
  toggleBorder: '#6B8096',
  contactMeButtonText: '#000',
  contactMeButtonBackground: '#fff',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#fff',
  seeMoreButtonText: '#fff',
  commentsBackground: '#fff',
  commentsInput: '#780000',
  commentsBubble: '#E2E2E2',
};
