export const lightTheme = {
  primary: '#fff',
  secondary: '#f5f3f4',
  accent: '#202020',
  text: '#000',
  toggleBorder: '#000',
  contactMeButtonText: '#fff',
  contactMeButtonBackground: '#000',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#000',
  seeMoreButtonText: '#000',
  commentsBackground: '#fff',
  commentsInput: '#E2E2E2',
  commentsBubble: '#E2E2E2',
};

export const darkTheme = {
  primary: '#1b1c22',
  secondary: '#4f5669',
  accent: '#fff',
  text: '#fff',
  toggleBorder: '#6B8096',
  contactMeButtonText: '#000',
  contactMeButtonBackground: '#fff',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#fff',
  seeMoreButtonText: '#fff',
  commentsBackground: '#fff',
  commentsInput: '#000',
  commentsBubble: '#E2E2E2',
};

export const blueTheme = {
  primary: '#118ab2',
  secondary: '#023047',
  accent: '#001d3d',
  text: '#fff',
  toggleBorder: '#6B8096',
  contactMeButtonText: '#fff',
  contactMeButtonBackground: '#000',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#fff',
  seeMoreButtonText: '#000',
  commentsBackground: '#fff',
  commentsInput: '#219ebc',
  commentsBubble: '#E2E2E2',
};

export const redTheme = {
  primary: '#6a040f',
  secondary: '#f7b538',
  accent: '#fdf0d5',
  text: '#fff',
  toggleBorder: '#6B8096',
  contactMeButtonText: '#000',
  contactMeButtonBackground: '#fff',
  contactMeBackground: '#000',
  contactMeButtonInputBackground: '#fff',
  contactMeButtonInputPlaceholder: '#fff',
  seeMoreButtonText: '#fff',
  commentsBackground: '#fff',
  commentsInput: '#780000',
  commentsBubble: '#E2E2E2',
};
